import Head from "next/head";
import {Week} from "@/interfaces/Week";
import {NextPage} from "next";
import {ActivityMapInterface} from "@/interfaces/ActivityMapInterface";
import ActivityMap from "@/components/ActivityMap/ActivityMap";

const Index: NextPage<ActivityMapInterface> = (props) => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main style={{margin: '100px'}}>
                <ActivityMap {...props}/>
            </main>
        </>
    );
}

export default Index

const findMax = (array: Week[]) => {
    let max = 0

    for (let i = 0; i < array.length; i++) {
        for (let j = 0; j < array[i].days.length; j++) {
            if (array[i].days[j] > max) {
                max = array[i].days[j]
            }
        }
    }

    return max
}

const groupMonths = (array: Week[]) => {

    const groups: Record<number, number> = {}

    array.forEach(week => {
        const month = new Date(week.week * 1000).getMonth()

        if (groups[month]) {
            groups[month] = groups[month] + 1
        } else {
            groups[month] = 1
        }

    })

    return groups

}

export const getStaticProps = async () => {

    const response = await fetch('https://api.github.com/repos/facebook/react/stats/commit_activity')
    const data = await response.json()
    const weeksByMonth = groupMonths(data)
    const maxActivityPerDay = findMax(data)

    return {
        props: {
            activity: data,
            weeksByMonth,
            maxActivityPerDay
        },
        revalidate: 600
    }

}
